modLoader="javafml"
loaderVersion="[55,)"
license="GPL-3.0-or-later"
clientSideOnly=true

[[mods]]
modId="wurstpenguin"
version="${version}"
displayName="WurstB+ Plus"
logoFile="assets/wurst/icon.png"
authors="Penguin"
displayTest="IGNORE_ALL_VERSION"
description='''
WurstB+ Plus for Minecraft 1.21.5.
'''

[[dependencies.wurstpenguin]]
modId="forge"
mandatory=true
versionRange="[55.1.0,56)"
ordering="NONE"
side="CLIENT"

[[dependencies.wurstpenguin]]
modId="minecraft"
mandatory=true
versionRange="[1.21.5,1.21.6)"
ordering="NONE"
side="CLIENT"
