org.gradle.jvmargs=-Xmx3G -Djavax.net.ssl.trustAll=true
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1.2
forge_version=64.1.0
mixinextras_version=0.4.1

mod_id=wurstpenguin
mod_version=v1.5.0-Forge-26.1.2
mod_authors=Penguin
maven_group=net.wurstpenguin
archives_base_name=WurstB+ Plus
