org.gradle.jvmargs=-Xmx3G -Djavax.net.ssl.trustAll=true
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1
forge_version=62.0.9
mixinextras_version=0.5.4

mod_id=wurstpenguin
mod_version=v1.5.0-Forge-26.1
mod_authors=Penguin
maven_group=net.wurstpenguin
archives_base_name=WurstB+ Plus
minecraft_version_range=[26.1,26.2)
