modLoader="javafml"
loaderVersion="[50,)"
license="GPL-3.0-or-later"
clientSideOnly=true

[[mods]]
modId="wurstpenguin"
version="${version}"
displayName="WurstB+ Plus"
logoFile="assets/wurst/icon.png"
authors="Penguin"
displayTest="IGNORE_ALL_VERSION"
description='''
WurstB+ Plus for Minecraft 1.20.6.
'''

[[dependencies.wurstpenguin]]
modId="forge"
mandatory=true
versionRange="[50.2.0,51)"
ordering="NONE"
side="CLIENT"

[[dependencies.wurstpenguin]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6,1.20.7)"
ordering="NONE"
side="CLIENT"
