modLoader="javafml"
loaderVersion="[61,)"
license="GPL-3.0-or-later"
clientSideOnly=true

[[mods]]
modId="wurstpenguin"
version="${version}"
displayName="WurstB+ Plus"
logoFile="assets/wurst/icon.png"
authors="Penguin"
displayTest="IGNORE_ALL_VERSION"
description='''
WurstB+ Plus for Minecraft 1.21.11.
'''

[[dependencies.wurstpenguin]]
modId="forge"
mandatory=true
versionRange="[61.2.0,62)"
ordering="NONE"
side="CLIENT"

[[dependencies.wurstpenguin]]
modId="minecraft"
mandatory=true
versionRange="[1.21.11,1.21.12)"
ordering="NONE"
side="CLIENT"
