plugins {
	id "java-library"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "net.neoforged.gradle.userdev" version "7.0.184"
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = "WurstB+ Plus"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
	main {
		java {
			exclude "net/wurstclient/clickgui2/component.disabled/**"
		}
		resources {
			srcDir "src/main/templates"
		}
	}
}

repositories {
	maven {
		name = "Sponge"
		url = "https://repo.spongepowered.org/repository/maven-public/"
	}
	mavenCentral()
	flatDir {
		dirs "."
	}
}

dependencies {
	implementation "net.neoforged:neoforge:${project.neo_version}"
	annotationProcessor "io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"
	compileOnly "io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"
	implementation "org.java-websocket:Java-WebSocket:1.5.3"
	implementation "io.netty:netty-codec-socks:4.1.82.Final"
	implementation "io.netty:netty-handler-proxy:4.1.82.Final"
	implementation files("baritone-api-forge-1.20.1.jar")
	compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

minecraft {
	accessTransformers {
		file "src/main/resources/META-INF/accesstransformer.cfg"
	}
}

runs {
	configureEach {
		workingDirectory project.file("run")
		systemProperty "forge.logging.markers", "REGISTRIES"
		systemProperty "forge.logging.console.level", "debug"
		modSource project.sourceSets.main
	}
	client {
		client()
	}
}

processResources {
	def displayVersion = project.version.toString().startsWith("v")
		? project.version.toString().substring(1)
		: project.version.toString()
	def replaceProperties = [
		minecraft_version      : minecraft_version,
		minecraft_version_range: minecraft_version_range,
		neo_version            : neo_version,
		neo_version_range      : neo_version_range,
		loader_version_range   : loader_version_range,
		mod_id                 : mod_id,
		mod_name               : mod_name,
		mod_license            : mod_license,
		mod_authors            : mod_authors,
		mod_version            : displayVersion,
	]
	inputs.properties replaceProperties
	filesMatching(["META-INF/neoforge.mods.toml", "META-INF/mods.toml", "wurst.mixins.json"]) {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release = 17
}

java {
	withSourcesJar()
}

jar {
	archiveFileName = "${project.base.archivesName.get()}-${project.version}.jar"
	manifest {
		attributes(
			"MixinConfigs": "wurst.mixins.json",
			"Specification-Title": project.mod_id,
			"Specification-Vendor": project.mod_authors,
			"Specification-Version": "1",
			"Implementation-Title": project.name,
			"Implementation-Version": project.version,
			"Implementation-Vendor": project.mod_authors)
	}
	from("LICENSE.txt") {
		rename { "LICENSE-${project.base.archivesName.get()}.txt" }
	}
	exclude "intentionally_untranslated.json"
}
