/*
 * Copyright (c) 2014-2025 Wurst-Imperium and contributors.
 *
 * This source code is subject to the terms of the GNU General Public
 * License, version 3. If a copy of the GPL was not distributed with this
 * file, You can obtain one at: https://www.gnu.org/licenses/gpl-3.0.txt
 */
package net.wurstclient.seed.scan;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Recognises structures in the chunks the client has already loaded, so that a
 * seed can be solved from what the player can see instead of from coordinates
 * they would have to type in by hand.
 *
 * <p>
 * <b>Every detector in here is a heuristic, so both missed structures and false
 * reports are possible.</b> Only block ids are looked at - never structure
 * starts, structure references or loot tables - which means:
 *
 * <ul>
 * <li>Anything a player built by hand looks exactly like a generated structure,
 * so a prismarine farm can be reported as an ocean monument.</li>
 * <li>A structure that is only partly loaded, or that is cut off by the scanned
 * y range, can stay below its thresholds.</li>
 * <li>A chunk can contain blocks of two sets at once, and this class reports
 * both of them.</li>
 * </ul>
 *
 * Anything reported here should be re-checked with {@code .seed structures}
 * before it is fed into a seed search.
 *
 * <p>
 * Each detector counts blocks per chunk inside its own y range and needs both a
 * block that the structure is built from and a block that the surrounding
 * terrain does not have:
 *
 * <ul>
 * <li>{@code minecraft:ocean_monuments}: {@value #MONUMENT_MIN_SEA_LANTERNS}+
 * sea lanterns and {@value #MONUMENT_MIN_PRISMARINES}+ prismarine blocks
 * between y {@value #MONUMENT_MIN_Y} and {@value #MONUMENT_MAX_Y}. Prismarine
 * and sea lanterns are only generated by ocean monuments (ocean ruins are made
 * of sand and gravel), so this cannot fire on natural ocean terrain.</li>
 * <li>{@code minecraft:ancient_cities}: either
 * {@value #ANCIENT_CITY_MIN_REINFORCED_DEEPSLATE}+ reinforced deepslate or
 * {@value #ANCIENT_CITY_MIN_DEEPSLATE_BRICKS}+ deepslate bricks together with
 * {@value #ANCIENT_CITY_MIN_DEEPSLATE_TILES}+ deepslate tiles, below y
 * {@value #ANCIENT_CITY_MAX_Y}. Plain deepslate and blackstone terrain does not
 * contain bricks or tiles, so the y limit plus the brick requirement is what
 * separates a city from the deep dark.</li>
 * <li>{@code minecraft:trail_ruins}: {@value #TRAIL_RUINS_MIN_MUD_BRICKS}+ mud
 * bricks between y {@value #TRAIL_RUINS_MIN_Y} and
 * {@value #TRAIL_RUINS_MAX_Y}. Trail ruins are the only place mud bricks
 * generate.</li>
 * <li>{@code minecraft:desert_pyramids}:
 * {@value #DESERT_PYRAMID_MIN_CHISELED_SANDSTONE}+ chiseled sandstone,
 * {@value #DESERT_PYRAMID_MIN_SHAPED_SANDSTONE}+ chiseled and cut sandstone
 * combined, and {@value #DESERT_PYRAMID_MIN_ORANGE_TERRACOTTA}+ orange
 * terracotta between y {@value #DESERT_PYRAMID_MIN_Y} and
 * {@value #DESERT_PYRAMID_MAX_Y}. Chiseled and cut sandstone do not generate in
 * deserts at all, and orange terracotta only does in badlands, so both parts of
 * the combination are needed.</li>
 * <li>{@code minecraft:igloos}: {@value #IGLOO_MIN_SNOW_BLOCKS}+ snow blocks
 * and {@value #IGLOO_MIN_INTERIOR_BLOCKS}+ interior blocks between y
 * {@value #IGLOO_MIN_Y} and {@value #IGLOO_MAX_Y}. Snowy biomes are covered in
 * snow blocks, so the snow alone means nothing and the interior decides.
 * White wool counts as an interior block, but vanilla igloos are built from a
 * template that uses white carpet, a red bed, a redstone torch and an oak
 * trapdoor instead, so all of those are accepted as well.</li>
 * <li>{@code minecraft:buried_treasures}: exactly
 * {@value #BURIED_TREASURE_CHESTS} chest between y
 * {@value #BURIED_TREASURE_MIN_Y} and {@value #BURIED_TREASURE_MAX_Y} in a
 * chunk whose biome is one of {@link #BURIED_TREASURE_BIOMES}. If the biome is
 * unknown, nothing is reported. A beached shipwreck, an ocean ruin or a dungeon
 * under a beach has a chest too, which is the known weak spot of this
 * detector.</li>
 * </ul>
 */
public final class StructureScanner
{
	/**
	 * The block and biome queries the scan needs. Implementations read from
	 * wherever they want - the client level, a cache or a test - and must
	 * return {@code null} instead of throwing when something is not available.
	 */
	public interface BlockView
	{
		/**
		 * @return the block id, e.g. {@code "minecraft:prismarine"}, or
		 *         {@code null} if the position is not loaded.
		 */
		String blockId(int x, int y, int z);
		
		/**
		 * @return whether this chunk is loaded, so that its block ids mean
		 *         anything.
		 */
		boolean isLoaded(int chunkX, int chunkZ);
		
		/**
		 * @return the biome id, e.g. {@code "minecraft:beach"}, or
		 *         {@code null} if it cannot be determined.
		 */
		default String biomeId(int x, int z)
		{
			return null;
		}
	}
	
	/**
	 * One structure set that was recognised in one chunk.
	 */
	public static final class Sighting
	{
		/** e.g. {@code "minecraft:ocean_monuments"}. */
		public final String setId;
		
		public final int chunkX;
		public final int chunkZ;
		
		/**
		 * The weight of the matching blocks. Higher is better and the list
		 * returned by {@link #scan} is sorted by this, but scores of different
		 * structure sets are not comparable.
		 */
		public final int score;
		
		/** e.g. {@code "3x sea_lantern + 41x prismarine"}. */
		public final String reason;
		
		public Sighting(String setId, int chunkX, int chunkZ, int score,
			String reason)
		{
			this.setId = setId;
			this.chunkX = chunkX;
			this.chunkZ = chunkZ;
			this.score = score;
			this.reason = reason;
		}
		
		public int blockX()
		{
			return chunkX * 16 + 8;
		}
		
		public int blockZ()
		{
			return chunkZ * 16 + 8;
		}
		
		public String describe()
		{
			return shortName(setId) + " at chunk [" + chunkX + ", " + chunkZ
				+ "] block [" + blockX() + ", " + blockZ() + "] score " + score
				+ " (" + reason + ")";
		}
		
		@Override
		public String toString()
		{
			return describe();
		}
	}
	
	public static final String OCEAN_MONUMENTS = "minecraft:ocean_monuments";
	public static final String ANCIENT_CITIES = "minecraft:ancient_cities";
	public static final String TRAIL_RUINS = "minecraft:trail_ruins";
	public static final String DESERT_PYRAMIDS = "minecraft:desert_pyramids";
	public static final String IGLOOS = "minecraft:igloos";
	public static final String BURIED_TREASURES = "minecraft:buried_treasures";
	
	private static final List<String> SUPPORTED_SETS =
		List.of(OCEAN_MONUMENTS, ANCIENT_CITIES, TRAIL_RUINS, DESERT_PYRAMIDS,
			IGLOOS, BURIED_TREASURES);
	
	/**
	 * The y range that is looked at at all. Everything a natural overworld
	 * structure can place is inside it, and blocks above it (a sky base, a
	 * beacon pyramid) are ignored on purpose.
	 */
	public static final int SCAN_MIN_Y = -64;
	public static final int SCAN_MAX_Y = 128;
	
	/**
	 * How far the scan may reach, in chunks per axis. Larger radii read far
	 * more chunks than a client-side observation needs.
	 */
	public static final int MAX_RADIUS_CHUNKS = 32;
	
	// ocean monuments
	public static final int MONUMENT_MIN_SEA_LANTERNS = 2;
	public static final int MONUMENT_MIN_PRISMARINES = 16;
	public static final int MONUMENT_SEA_LANTERN_WEIGHT = 8;
	public static final int MONUMENT_MIN_Y = 20;
	public static final int MONUMENT_MAX_Y = 80;
	
	// ancient cities
	public static final int ANCIENT_CITY_MIN_REINFORCED_DEEPSLATE = 1;
	public static final int ANCIENT_CITY_MIN_DEEPSLATE_BRICKS = 24;
	public static final int ANCIENT_CITY_MIN_DEEPSLATE_TILES = 8;
	public static final int ANCIENT_CITY_REINFORCED_WEIGHT = 12;
	public static final int ANCIENT_CITY_MIN_Y = -64;
	/** Exclusive upper bound: an ancient city is always below y=0. */
	public static final int ANCIENT_CITY_MAX_Y = -1;
	
	// trail ruins
	public static final int TRAIL_RUINS_MIN_MUD_BRICKS = 8;
	public static final int TRAIL_RUINS_MIN_Y = -64;
	public static final int TRAIL_RUINS_MAX_Y = 80;
	
	// desert pyramids
	public static final int DESERT_PYRAMID_MIN_CHISELED_SANDSTONE = 2;
	public static final int DESERT_PYRAMID_MIN_SHAPED_SANDSTONE = 8;
	public static final int DESERT_PYRAMID_MIN_ORANGE_TERRACOTTA = 4;
	public static final int DESERT_PYRAMID_CHISELED_WEIGHT = 4;
	public static final int DESERT_PYRAMID_TERRACOTTA_WEIGHT = 4;
	public static final int DESERT_PYRAMID_MIN_Y = 50;
	public static final int DESERT_PYRAMID_MAX_Y = 128;
	
	// igloos
	public static final int IGLOO_MIN_SNOW_BLOCKS = 16;
	public static final int IGLOO_MIN_INTERIOR_BLOCKS = 2;
	public static final int IGLOO_INTERIOR_WEIGHT = 8;
	public static final int IGLOO_MIN_Y = 50;
	public static final int IGLOO_MAX_Y = 128;
	
	// buried treasures
	public static final int BURIED_TREASURE_CHESTS = 1;
	public static final int BURIED_TREASURE_CHEST_WEIGHT = 20;
	public static final int BURIED_TREASURE_MIN_Y = 24;
	public static final int BURIED_TREASURE_MAX_Y = 80;
	public static final List<String> BURIED_TREASURE_BIOMES = List
		.of("minecraft:beach", "minecraft:snowy_beach", "minecraft:stony_shore");
	
	private static final String PRISMARINE = "minecraft:prismarine";
	private static final String PRISMARINE_BRICKS = "minecraft:prismarine_bricks";
	private static final String DARK_PRISMARINE = "minecraft:dark_prismarine";
	private static final String SEA_LANTERN = "minecraft:sea_lantern";
	private static final String REINFORCED_DEEPSLATE =
		"minecraft:reinforced_deepslate";
	private static final String DEEPSLATE_BRICKS = "minecraft:deepslate_bricks";
	private static final String DEEPSLATE_TILES = "minecraft:deepslate_tiles";
	private static final String MUD_BRICKS = "minecraft:mud_bricks";
	private static final String CHISELED_SANDSTONE =
		"minecraft:chiseled_sandstone";
	private static final String CUT_SANDSTONE = "minecraft:cut_sandstone";
	private static final String ORANGE_TERRACOTTA =
		"minecraft:orange_terracotta";
	private static final String SNOW_BLOCK = "minecraft:snow_block";
	private static final String WHITE_WOOL = "minecraft:white_wool";
	private static final String WHITE_CARPET = "minecraft:white_carpet";
	private static final String LIGHT_GRAY_CARPET =
		"minecraft:light_gray_carpet";
	private static final String RED_BED = "minecraft:red_bed";
	private static final String REDSTONE_TORCH = "minecraft:redstone_torch";
	private static final String OAK_TRAPDOOR = "minecraft:oak_trapdoor";
	private static final String CHEST = "minecraft:chest";
	
	/**
	 * Scans the square of chunks around a centre chunk.
	 *
	 * @param view         the blocks to read, or {@code null} for no result
	 * @param centerChunkX centre chunk, may be negative
	 * @param centerChunkZ centre chunk, may be negative
	 * @param radiusChunks chunks per axis in Chebyshev distance, clamped to
	 *                     {@value #MAX_RADIUS_CHUNKS}
	 * @return one sighting per chunk and structure set, best score first.
	 */
	public static List<Sighting> scan(BlockView view, int centerChunkX,
		int centerChunkZ, int radiusChunks)
	{
		ArrayList<Sighting> sightings = new ArrayList<>();
		
		if(view == null)
			return sightings;
		
		int radius = Math.max(0, Math.min(radiusChunks, MAX_RADIUS_CHUNKS));
		
		for(int chunkX = centerChunkX - radius; chunkX <= centerChunkX
			+ radius; chunkX++)
			for(int chunkZ = centerChunkZ - radius; chunkZ <= centerChunkZ
				+ radius; chunkZ++)
				scanChunk(sightings, view, chunkX, chunkZ);
		
		sightings.sort(Comparator
			.comparingInt((Sighting sighting) -> sighting.score).reversed()
			.thenComparingInt(sighting -> distance(sighting, centerChunkX,
				centerChunkZ))
			.thenComparing(sighting -> sighting.setId)
			.thenComparingInt(sighting -> sighting.chunkX)
			.thenComparingInt(sighting -> sighting.chunkZ));
		
		return sightings;
	}
	
	/**
	 * @return the structure set ids this scanner can recognise, sorted as they
	 *         are documented above.
	 */
	public static List<String> supportedSets()
	{
		return SUPPORTED_SETS;
	}
	
	private static void scanChunk(ArrayList<Sighting> sightings, BlockView view,
		int chunkX, int chunkZ)
	{
		if(!view.isLoaded(chunkX, chunkZ))
			return;
		
		Tally tally = new Tally();
		int minX = chunkX * 16;
		int minZ = chunkZ * 16;
		
		try
		{
			// one pass per chunk over the whole scanned y range, so that a
			// section that cannot be read cannot stop the other detectors
			for(int y = SCAN_MIN_Y; y <= SCAN_MAX_Y; y++)
				for(int x = minX; x < minX + 16; x++)
					for(int z = minZ; z < minZ + 16; z++)
					{
						String id = view.blockId(x, y, z);
						
						if(id != null)
							count(tally, id, x, y, z);
					}
			
			collect(sightings, view, tally, chunkX, chunkZ);
		}catch(Exception e)
		{
			// an unreadable chunk is skipped, the rest of the scan is still
			// worth reporting
		}
	}
	
	/**
	 * Adds one block to the tally of every detector that watches it. The y
	 * ranges live here as well, so that no counter can be fed from outside its
	 * detector's range.
	 */
	private static void count(Tally tally, String id, int x, int y, int z)
	{
		switch(id)
		{
			case PRISMARINE:
			case PRISMARINE_BRICKS:
			case DARK_PRISMARINE:
			if(y >= MONUMENT_MIN_Y && y <= MONUMENT_MAX_Y)
				tally.prismarines++;
			break;
			
			case SEA_LANTERN:
			if(y >= MONUMENT_MIN_Y && y <= MONUMENT_MAX_Y)
				tally.seaLanterns++;
			break;
			
			case REINFORCED_DEEPSLATE:
			if(y >= ANCIENT_CITY_MIN_Y && y <= ANCIENT_CITY_MAX_Y)
				tally.reinforcedDeepslate++;
			break;
			
			case DEEPSLATE_BRICKS:
			if(y >= ANCIENT_CITY_MIN_Y && y <= ANCIENT_CITY_MAX_Y)
				tally.deepslateBricks++;
			break;
			
			case DEEPSLATE_TILES:
			if(y >= ANCIENT_CITY_MIN_Y && y <= ANCIENT_CITY_MAX_Y)
				tally.deepslateTiles++;
			break;
			
			case MUD_BRICKS:
			if(y >= TRAIL_RUINS_MIN_Y && y <= TRAIL_RUINS_MAX_Y)
				tally.mudBricks++;
			break;
			
			case CHISELED_SANDSTONE:
			if(y >= DESERT_PYRAMID_MIN_Y && y <= DESERT_PYRAMID_MAX_Y)
				tally.chiseledSandstone++;
			break;
			
			case CUT_SANDSTONE:
			if(y >= DESERT_PYRAMID_MIN_Y && y <= DESERT_PYRAMID_MAX_Y)
				tally.cutSandstone++;
			break;
			
			case ORANGE_TERRACOTTA:
			if(y >= DESERT_PYRAMID_MIN_Y && y <= DESERT_PYRAMID_MAX_Y)
				tally.orangeTerracotta++;
			break;
			
			case SNOW_BLOCK:
			if(y >= IGLOO_MIN_Y && y <= IGLOO_MAX_Y)
				tally.snowBlocks++;
			break;
			
			case WHITE_WOOL:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.whiteWools++;
			break;
			
			case WHITE_CARPET:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.whiteCarpets++;
			break;
			
			case LIGHT_GRAY_CARPET:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.lightGrayCarpets++;
			break;
			
			case RED_BED:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.redBeds++;
			break;
			
			case REDSTONE_TORCH:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.redstoneTorches++;
			break;
			
			case OAK_TRAPDOOR:
			if(y < IGLOO_MIN_Y || y > IGLOO_MAX_Y)
				break;
			tally.oakTrapdoors++;
			break;
			
			case CHEST:
			if(y < BURIED_TREASURE_MIN_Y || y > BURIED_TREASURE_MAX_Y)
				break;
			tally.chests++;
			
			// the biome is only asked for once a chest was found, because
			// that is the only detector that needs it
			if(!tally.chestFound)
			{
				tally.chestFound = true;
				tally.chestX = x;
				tally.chestY = y;
				tally.chestZ = z;
			}
			break;
			
			default:
			break;
		}
	}
	
	private static void collect(ArrayList<Sighting> sightings, BlockView view,
		Tally tally, int chunkX, int chunkZ)
	{
		add(sightings, judgeMonument(tally, chunkX, chunkZ));
		add(sightings, judgeAncientCity(tally, chunkX, chunkZ));
		add(sightings, judgeTrailRuins(tally, chunkX, chunkZ));
		add(sightings, judgeDesertPyramid(tally, chunkX, chunkZ));
		add(sightings, judgeIgloo(tally, chunkX, chunkZ));
		add(sightings, judgeBuriedTreasure(view, tally, chunkX, chunkZ));
	}
	
	private static void add(ArrayList<Sighting> sightings, Sighting sighting)
	{
		if(sighting != null)
			sightings.add(sighting);
	}
	
	private static Sighting judgeMonument(Tally tally, int chunkX, int chunkZ)
	{
		if(tally.seaLanterns < MONUMENT_MIN_SEA_LANTERNS
			|| tally.prismarines < MONUMENT_MIN_PRISMARINES)
			return null;
		
		int score = tally.seaLanterns * MONUMENT_SEA_LANTERN_WEIGHT
			+ tally.prismarines;
		StringBuilder reason = new StringBuilder();
		append(reason, tally.seaLanterns, "sea_lantern");
		append(reason, tally.prismarines, "prismarine");
		
		return new Sighting(OCEAN_MONUMENTS, chunkX, chunkZ, score,
			reason.toString());
	}
	
	private static Sighting judgeAncientCity(Tally tally, int chunkX,
		int chunkZ)
	{
		boolean reinforced = tally.reinforcedDeepslate
			>= ANCIENT_CITY_MIN_REINFORCED_DEEPSLATE;
		boolean built = tally.deepslateBricks >= ANCIENT_CITY_MIN_DEEPSLATE_BRICKS
			&& tally.deepslateTiles >= ANCIENT_CITY_MIN_DEEPSLATE_TILES;
		
		if(!reinforced && !built)
			return null;
		
		int score = tally.reinforcedDeepslate * ANCIENT_CITY_REINFORCED_WEIGHT
			+ tally.deepslateBricks + tally.deepslateTiles;
		StringBuilder reason = new StringBuilder();
		append(reason, tally.reinforcedDeepslate, "reinforced_deepslate");
		append(reason, tally.deepslateBricks, "deepslate_bricks");
		append(reason, tally.deepslateTiles, "deepslate_tiles");
		
		return new Sighting(ANCIENT_CITIES, chunkX, chunkZ, score,
			reason.toString());
	}
	
	private static Sighting judgeTrailRuins(Tally tally, int chunkX, int chunkZ)
	{
		if(tally.mudBricks < TRAIL_RUINS_MIN_MUD_BRICKS)
			return null;
		
		StringBuilder reason = new StringBuilder();
		append(reason, tally.mudBricks, "mud_bricks");
		
		return new Sighting(TRAIL_RUINS, chunkX, chunkZ, tally.mudBricks,
			reason.toString());
	}
	
	private static Sighting judgeDesertPyramid(Tally tally, int chunkX,
		int chunkZ)
	{
		int shaped = tally.chiseledSandstone + tally.cutSandstone;
		
		if(tally.chiseledSandstone < DESERT_PYRAMID_MIN_CHISELED_SANDSTONE
			|| shaped < DESERT_PYRAMID_MIN_SHAPED_SANDSTONE
			|| tally.orangeTerracotta < DESERT_PYRAMID_MIN_ORANGE_TERRACOTTA)
			return null;
		
		int score = tally.chiseledSandstone * DESERT_PYRAMID_CHISELED_WEIGHT
			+ shaped
			+ tally.orangeTerracotta * DESERT_PYRAMID_TERRACOTTA_WEIGHT;
		StringBuilder reason = new StringBuilder();
		append(reason, tally.chiseledSandstone, "chiseled_sandstone");
		append(reason, tally.cutSandstone, "cut_sandstone");
		append(reason, tally.orangeTerracotta, "orange_terracotta");
		
		return new Sighting(DESERT_PYRAMIDS, chunkX, chunkZ, score,
			reason.toString());
	}
	
	private static Sighting judgeIgloo(Tally tally, int chunkX, int chunkZ)
	{
		int interiors = tally.whiteWools + tally.whiteCarpets
			+ tally.lightGrayCarpets + tally.redBeds + tally.redstoneTorches
			+ tally.oakTrapdoors;
		
		if(tally.snowBlocks < IGLOO_MIN_SNOW_BLOCKS
			|| interiors < IGLOO_MIN_INTERIOR_BLOCKS)
			return null;
		
		int score = tally.snowBlocks + interiors * IGLOO_INTERIOR_WEIGHT;
		StringBuilder reason = new StringBuilder();
		append(reason, tally.snowBlocks, "snow_block");
		append(reason, tally.whiteWools, "white_wool");
		append(reason, tally.whiteCarpets, "white_carpet");
		append(reason, tally.lightGrayCarpets, "light_gray_carpet");
		append(reason, tally.redBeds, "red_bed");
		append(reason, tally.redstoneTorches, "redstone_torch");
		append(reason, tally.oakTrapdoors, "oak_trapdoor");
		
		return new Sighting(IGLOOS, chunkX, chunkZ, score, reason.toString());
	}
	
	private static Sighting judgeBuriedTreasure(BlockView view, Tally tally,
		int chunkX, int chunkZ)
	{
		if(tally.chests != BURIED_TREASURE_CHESTS)
			return null;
		
		String biome = view.biomeId(tally.chestX, tally.chestZ);
		
		// an unknown biome is not a beach, so nothing is reported
		if(biome == null || !BURIED_TREASURE_BIOMES.contains(biome))
			return null;
		
		StringBuilder reason = new StringBuilder();
		append(reason, tally.chests, "chest");
		reason.append(" at y=").append(tally.chestY);
		reason.append(" in ").append(shortName(biome));
		
		return new Sighting(BURIED_TREASURES, chunkX, chunkZ,
			tally.chests * BURIED_TREASURE_CHEST_WEIGHT, reason.toString());
	}
	
	private static void append(StringBuilder builder, int count, String name)
	{
		if(count <= 0)
			return;
		
		if(builder.length() > 0)
			builder.append(" + ");
		
		builder.append(count).append("x ").append(name);
	}
	
	private static int distance(Sighting sighting, int centerChunkX,
		int centerChunkZ)
	{
		return Math.max(Math.abs(sighting.chunkX - centerChunkX),
			Math.abs(sighting.chunkZ - centerChunkZ));
	}
	
	private static String shortName(String id)
	{
		if(id == null)
			return "?";
		
		int colon = id.indexOf(':');
		return colon < 0 ? id : id.substring(colon + 1);
	}
	
	/**
	 * The counters of one chunk. Every field belongs to exactly one detector
	 * and is only written inside that detector's y range.
	 */
	private static final class Tally
	{
		private int seaLanterns;
		private int prismarines;
		private int reinforcedDeepslate;
		private int deepslateBricks;
		private int deepslateTiles;
		private int mudBricks;
		private int chiseledSandstone;
		private int cutSandstone;
		private int orangeTerracotta;
		private int snowBlocks;
		private int whiteWools;
		private int whiteCarpets;
		private int lightGrayCarpets;
		private int redBeds;
		private int redstoneTorches;
		private int oakTrapdoors;
		private int chests;
		private boolean chestFound;
		private int chestX;
		private int chestY;
		private int chestZ;
	}
}
